{
	"IsEnabled": true,
	"Name": "DevkitServer",
	"Version": "0.0.0.1",
	"Assemblies":
	[
		{
			"Path": "/Libraries/0Harmony.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/StackCleaner.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/System.Runtime.CompilerServices.Unsafe.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/System.Text.Encodings.Web.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/Microsoft.Bcl.AsyncInterfaces.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/System.Memory.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/System.Buffers.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/System.Numerics.Vectors.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/System.ValueTuple.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/System.Threading.Tasks.Extensions.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/System.IO.Compression.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/System.IO.Compression.FileSystem.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/System.Text.Json.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/UniTask.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Bin/DevkitServer_Server.dll",
			"Role": "Server"
		},
		{
			"Path": "/Bin/DevkitServer_Client.dll",
			"Role": "Client"
		}
	]
}
