{
	"IsEnabled": true,
	"Name": "DevkitServer",
	"Version": "0.0.0.0",
	"Dependencies":
	[
		{
			"Name": "DevkitServer.Launcher",
			"Version": "1.0.0.3"
		}
	],
	"Assemblies":
	[
		{
			"Path": "/Libraries/Lib.Harmony/0Harmony.dll",
			"Role": "Both_Optional",
			"Load_As_Byte_Array": false
		},
		{
			"Path": "/Bin/DevkitServer_Server.dll",
			"Role": "Server",
			"Load_As_Byte_Array": false
		},
		{
			"Path": "/Bin/DevkitServer_Client.dll",
			"Role": "Client",
			"Load_As_Byte_Array": false
		}
	]
}