//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevkitServer.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        internal static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevkitServer.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] backup_config {
            get {
                object obj = ResourceManager.GetObject("backup_config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] backup_schema {
            get {
                object obj = ResourceManager.GetObject("backup_schema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cartography_compositor_pipeline_schema {
            get {
                object obj = ResourceManager.GetObject("cartography_compositor_pipeline_schema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cartography_config {
            get {
                object obj = ResourceManager.GetObject("cartography_config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cartography_config_schema {
            get {
                object obj = ResourceManager.GetObject("cartography_config_schema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] chart_colors {
            get {
                object obj = ResourceManager.GetObject("chart_colors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] chart_colors_schema {
            get {
                object obj = ResourceManager.GetObject("chart_colors_schema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] client_config {
            get {
                object obj = ResourceManager.GetObject("client_config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] client_config_schema {
            get {
                object obj = ResourceManager.GetObject("client_config_schema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DanielWillett_ReflectionTools {
            get {
                object obj = ResourceManager.GetObject("DanielWillett.ReflectionTools", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DanielWillett_ReflectionTools_Harmony {
            get {
                object obj = ResourceManager.GetObject("DanielWillett.ReflectionTools.Harmony", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DanielWillett_ReflectionTools_LICENSE {
            get {
                object obj = ResourceManager.GetObject("DanielWillett.ReflectionTools.LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DanielWillett_SpeedBytes {
            get {
                object obj = ResourceManager.GetObject("DanielWillett.SpeedBytes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DanielWillett_SpeedBytes_LICENSE {
            get {
                object obj = ResourceManager.GetObject("DanielWillett.SpeedBytes.LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DanielWillett_SpeedBytes_Unity {
            get {
                object obj = ResourceManager.GetObject("DanielWillett.SpeedBytes.Unity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DanielWillett_StackCleaner {
            get {
                object obj = ResourceManager.GetObject("DanielWillett.StackCleaner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DanielWillett_StackCleaner_LICENSE {
            get {
                object obj = ResourceManager.GetObject("DanielWillett.StackCleaner.LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DanielWillett_StackCleaner_Symbols {
            get {
                object obj = ResourceManager.GetObject("DanielWillett.StackCleaner.Symbols", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DanielWillett_StackCleaner_XmlDocs {
            get {
                object obj = ResourceManager.GetObject("DanielWillett.StackCleaner.XmlDocs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DevkitServer {
            get {
                object obj = ResourceManager.GetObject("DevkitServer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DevkitServer_LICENSE {
            get {
                object obj = ResourceManager.GetObject("DevkitServer.LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] devkitserver_linux_masterbundle {
            get {
                object obj = ResourceManager.GetObject("devkitserver_linux.masterbundle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] devkitserver_linux_masterbundle_manifest {
            get {
                object obj = ResourceManager.GetObject("devkitserver_linux.masterbundle.manifest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] devkitserver_mac_masterbundle {
            get {
                object obj = ResourceManager.GetObject("devkitserver_mac.masterbundle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] devkitserver_mac_masterbundle_manifest {
            get {
                object obj = ResourceManager.GetObject("devkitserver_mac.masterbundle.manifest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] devkitserver_masterbundle {
            get {
                object obj = ResourceManager.GetObject("devkitserver.masterbundle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] devkitserver_masterbundle_hash {
            get {
                object obj = ResourceManager.GetObject("devkitserver.masterbundle.hash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] devkitserver_masterbundle_manifest {
            get {
                object obj = ResourceManager.GetObject("devkitserver.masterbundle.manifest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] English {
            get {
                object obj = ResourceManager.GetObject("English", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FWD_DanielWillett_LevelObjectIcons {
            get {
                object obj = ResourceManager.GetObject("FWD.DanielWillett.LevelObjectIcons", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lib_Harmony {
            get {
                object obj = ResourceManager.GetObject("Lib.Harmony", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lib_Harmony_LICENSE {
            get {
                object obj = ResourceManager.GetObject("Lib.Harmony.LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MasterBundle {
            get {
                object obj = ResourceManager.GetObject("MasterBundle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Bcl_AsyncInterfaces {
            get {
                object obj = ResourceManager.GetObject("Microsoft.Bcl.AsyncInterfaces", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Bcl_AsyncInterfaces_LICENSE {
            get {
                object obj = ResourceManager.GetObject("Microsoft.Bcl.AsyncInterfaces.LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Bcl_HashCode {
            get {
                object obj = ResourceManager.GetObject("Microsoft.Bcl.HashCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Bcl_HashCode_LICENSE {
            get {
                object obj = ResourceManager.GetObject("Microsoft.Bcl.HashCode.LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Object_Icon_Presets__Vanilla_ {
            get {
                object obj = ResourceManager.GetObject("Object Icon Presets (Vanilla)", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] permission_groups {
            get {
                object obj = ResourceManager.GetObject("permission_groups", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] permission_groups_schema {
            get {
                object obj = ResourceManager.GetObject("permission_groups_schema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] server_config {
            get {
                object obj = ResourceManager.GetObject("server_config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] server_config_schema {
            get {
                object obj = ResourceManager.GetObject("server_config_schema", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Buffers {
            get {
                object obj = ResourceManager.GetObject("System.Buffers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Buffers_LICENSE {
            get {
                object obj = ResourceManager.GetObject("System.Buffers.LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Numerics_Vectors {
            get {
                object obj = ResourceManager.GetObject("System.Numerics.Vectors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Numerics_Vectors_LICENSE {
            get {
                object obj = ResourceManager.GetObject("System.Numerics.Vectors.LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Text_Encodings_Web {
            get {
                object obj = ResourceManager.GetObject("System.Text.Encodings.Web", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Text_Encodings_Web_LICENSE {
            get {
                object obj = ResourceManager.GetObject("System.Text.Encodings.Web.LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Text_Json {
            get {
                object obj = ResourceManager.GetObject("System.Text.Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Text_Json_LICENSE {
            get {
                object obj = ResourceManager.GetObject("System.Text.Json.LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Threading_Tasks_Extensions {
            get {
                object obj = ResourceManager.GetObject("System.Threading.Tasks.Extensions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_ValueTuple {
            get {
                object obj = ResourceManager.GetObject("System.ValueTuple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_ValueTuple_LICENSE {
            get {
                object obj = ResourceManager.GetObject("System.ValueTuple.LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UniTask {
            get {
                object obj = ResourceManager.GetObject("UniTask", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UniTask_Dependencies {
            get {
                object obj = ResourceManager.GetObject("UniTask.Dependencies", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UniTask_LICENSE {
            get {
                object obj = ResourceManager.GetObject("UniTask.LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UniTask_Symbols {
            get {
                object obj = ResourceManager.GetObject("UniTask.Symbols", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UniTask_XmlDocs {
            get {
                object obj = ResourceManager.GetObject("UniTask.XmlDocs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UnturnedUITools {
            get {
                object obj = ResourceManager.GetObject("UnturnedUITools", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UnturnedUITools_LICENSE {
            get {
                object obj = ResourceManager.GetObject("UnturnedUITools.LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UnturnedUITools_Symbols {
            get {
                object obj = ResourceManager.GetObject("UnturnedUITools.Symbols", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UnturnedUITools_XmlDocs {
            get {
                object obj = ResourceManager.GetObject("UnturnedUITools.XmlDocs", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
