{
	"IsEnabled": true,
	"Name": "DevkitServer.Launcher",
	"Version": "1.0.0.3",
	"Assemblies":
	[
		{
			"Path": "/Libraries/NuGet/NuGet.Common.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/NuGet/NuGet.Versioning.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/NuGet/NuGet.Configuration.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/NuGet/NuGet.Packaging.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/NuGet/NuGet.Frameworks.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/System.Xml.Linq/System.Xml.Linq.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/System.IO.Compression/System.IO.Compression.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Libraries/System.IO.Compression.FileSystem/System.IO.Compression.FileSystem.dll",
			"Role": "Both_Optional"
		},
		{
			"Path": "/Bin/DevkitServer.Launcher.dll",
			"Role": "Client"
		},
		{
			"Path": "/Bin/DevkitServer.Launcher.dll",
			"Role": "Server"
		}
	]
}
