on:
  workflow_dispatch:
    inputs:
      sem_version:
        description: "Version"
        required: true
        type: string
      change_notes:
        description: "Change Notes"
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: 'master'
        
    - name: SetupDotNet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '5.0.x'
        
    - name: Decode DevkitServer .snk
      uses: akiojin/decode-base64-github-action@v0.1.0
      id: decode-base64
      with:
        base64: ${{ secrets.DEVKITSERVER_SNK }}
        output-path: ${{ runner.temp }}/devkitserver.dll.snk
        
    - name: Build Server
      run: dotnet build "DevkitServer.csproj" --configuration ServerRelease "/p:Version=${{ inputs.sem_version }};PackageReleaseNotes=${{ inputs.change_notes }};IsInGitHubActions=True;AssemblyOriginatorKeyFile=${{ steps.decode-base64.outputs.output-path }};SignAssembly=True"

    - name: Build Client
      run: dotnet build "DevkitServer.csproj" --configuration ClientRelease "/p:Version=${{ inputs.sem_version }};PackageReleaseNotes=${{ inputs.change_notes }};IsInGitHubActions=True;AssemblyOriginatorKeyFile=${{ steps.decode-base64.outputs.output-path }};SignAssembly=True"
    
    - name: Test Server
      run: dotnet test "DevkitServer.Tests/DevkitServer.Tests.csproj" --configuration ServerRelease "/p:IsInGitHubActions=True;AssemblyOriginatorKeyFile=${{ steps.decode-base64.outputs.output-path }};SignAssembly=True"
      
    - name: Test Client
      run: dotnet test "DevkitServer.Tests/DevkitServer.Tests.csproj" --configuration ClientRelease "/p:IsInGitHubActions=True;AssemblyOriginatorKeyFile=${{ steps.decode-base64.outputs.output-path }};SignAssembly=True"
