on:
  workflow_dispatch:
    inputs:
      sem_version:
        description: "Version"
        required: true
        type: string
      change_notes:
        description: "Change Notes"
        required: true
        type: string
jobs:
  call-build:
    uses: ./.github/workflows/build_release.yml
    secrets: inherit
    with:
      sem_version: ${{ inputs.sem_version }}
      change_notes: ${{ inputs.change_notes }}
    
