on:
  workflow_dispatch:
    inputs:
      sem_version:
        description: "Version"
        required: true
        type: string
      change_notes:
        description: "Change Notes"
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: 'master'
    - name: Build Server
      run: dotnet build "DevkitServer.sln" --project "DevkitServer.csproj" --configuration ServerRelease "/p:Version=${{ inputs.sem_version }};PackageReleaseNotes=${{ inputs.change_notes }};IsInGitHubActions=True"
    - name: Test Server
      run: dotnet test "DevkitServer.sln" --project "DevkitServer.Tests/DevkitServer.Tests.csproj" --configuration ServerRelease "/p:IsInGitHubActions=True" --no-build
    - name: Build Client
      run: dotnet build "DevkitServer.sln" --project "DevkitServer.csproj" --configuration ClientRelease "/p:Version=${{ inputs.sem_version }};PackageReleaseNotes=${{ inputs.change_notes }};IsInGitHubActions=True"
    - name: Test Client
      run: dotnet test "DevkitServer.sln" --project "DevkitServer.Tests/DevkitServer.Tests.csproj" --configuration ClientRelease "/p:IsInGitHubActions=True" --no-build 
    - name: Pack Server
      run: dotnet pack "DevkitServer.sln" --project "DevkitServer.csproj" --configuration ServerRelease "/p:Version=${{ inputs.sem_version }};PackageReleaseNotes=${{ inputs.change_notes }};IsInGitHubActions=True" --no-build --output .
