on:
  workflow_dispatch:
    inputs:
      sem_version:
        description: "Version"
        required: true
        type: string
      change_notes:
        description: "Change Notes"
        required: true
        type: string
jobs:
  call-build:
    uses: ./.github/workflows/build_release.yml
    secrets: inherit
    with:
      sem_version: ${{ inputs.sem_version }}
      change_notes: ${{ inputs.change_notes }}
      
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Pack Server
      run: dotnet pack "DevkitServer.csproj" --configuration ServerRelease "/p:Version=${{ inputs.sem_version }};PackageReleaseNotes=${{ inputs.change_notes }};IsInGitHubActions=True;AssemblyOriginatorKeyFile=${{ steps.decode-base64.outputs.output-path }};SignAssembly=True" --no-build --output .
    
    - name: Pack Client
      run: dotnet pack "DevkitServer.csproj" --configuration ServerRelease "/p:Version=${{ inputs.sem_version }};PackageReleaseNotes=${{ inputs.change_notes }};IsInGitHubActions=True;AssemblyOriginatorKeyFile=${{ steps.decode-base64.outputs.output-path }};SignAssembly=True" --no-build --output .
  
